Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    CodeUri: ./src
    Runtime: nodejs24.x
    Timeout: 5
    MemorySize: 128
    Tags:
      project: practice
Resources:
  # 1. The Table (SAM Resource)
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      Tags:
        project: practice
      PrimaryKey:
        Name: id
        Type: String
  # 2. Get Todos
  GetTodosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          ALLOWED_ORIGIN: !GetAtt UiBucket.WebsiteURL
      Handler: getTodos.handler
      Events:
        GetTodos:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: GET
            ApiId: !Ref MyApi
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
  CreateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          ALLOWED_ORIGIN: !GetAtt UiBucket.WebsiteURL
      Handler: createTodo.handler
      Events:
        CreateTodo:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: POST
            ApiId: !Ref MyApi
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TodoTable
  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: project
          Value: practice
  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${UiBucket}/*'

  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - !GetAtt UiBucket.WebsiteURL
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/"
  WebsiteURL:
    Value: !GetAtt UiBucket.WebsiteURL
    Description: "URL for the hosted UI"
  UiBucketName:
    Value: !Ref UiBucket
    Description: "The name of the S3 bucket for the UI"
